name: C/C++ CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build_c
      run: cd src && gcc Helloworld.c -o ../build/test_c
    
    - name: build_cpp
      run: cd src && g++ Helloworld.cpp -o ../build/test_cpp
      
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: test
        path: build
